apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test_hubappswa
  annotations:
    jenkins.io/job-full-name: chief-hem-org-job/test_hubappswa
spec:
  type: website
  lifecycle: experimental
  owner: "team-a"
